/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: VRA (https://sketchfab.com/architect47)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rain-drops-circles-download-like-please-50b52de9b9a94ac09afbbaf28f102081
Title: Rain drops circles | Download = Like please
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Rain(props) {
  const { nodes, materials } = useGLTF('/model/rain_drops_circles__download__like_please.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                '������������_-_������������_������������_������������_-_������������_������������_0'
              ].geometry
            }
            material={materials.material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                '������������_-_������������-��������������������_15x15_������������_-_������������-��������������������_15x15_0'
              ].geometry
            }
            material={materials['-_-_15x15']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={
              nodes[
                '������������_-_��������������_����������_������������_-_��������������_����������_0'
              ].geometry
            }
            material={materials.material_2}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/rain_drops_circles__download__like_please.glb')

